spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/arbol_saberes}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
app.jwt.secret=${JWT_SECRET:ArbolSaberes2025SecretKeyMustBe32CharsLong!!}
app.jwt.expiration=${JWT_EXPIRATION:28800000}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=52MB
app.allowed.origins=${ALLOWED_ORIGINS:http://localhost:5173}
server.port=8080
